services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - NEXT_PUBLIC_CLIENT_API_URL=http://127.0.0.1:3000
        - NEXT_PUBLIC_APP_VERSION=1.0.0
    ports:
      - 3001:80
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=file:./dev.db
      - APP_VERSION=1.0.0
      - APP_ENV=development
